apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myteam-hellokubernetes-dev
spec:
  destination:
    namespace: myteam-myapp-dev
    server: https://kubernetes.default.svc
  project: myteam-myapp-dev
  source:
    path: yaml/dev
    repoURL: https://github.com/slaterin/hello-kubernetes.git
    targetRevision: master
